package com.thedavelopers.eventqr.features.organizer

object OrganizerMvpPlaceholders {
    const val TODO_BACKEND =
        "TODO: Replace organizer MVP sample data with repository/API calls once backend endpoints are finalized."

    val events = listOf(
        OrganizerMvpEvent(
            id = "evt-tech-2026",
            title = "Tech Summit 2026",
            dateTime = "May 30, 2026, 9:00 AM - 5:00 PM",
            venue = "Main Auditorium",
            status = "Approved",
            registeredCount = 128,
            enteredCount = 91,
            attendedCount = 87,
            exitedCount = 32,
            noShowCount = 37,
            totalTransactions = 246,
            rejectedScans = 8,
            benefitClaims = 54,
            boothSessionVisits = 63,
            rewardRedemptions = 17,
            totalPointsAwarded = 1840,
            idTemplateStatus = "Ready",
            rewardsStatus = "Enabled",
            staffCount = 6,
            scanPurposesCount = 6,
        ),
        OrganizerMvpEvent(
            id = "evt-career-2026",
            title = "Career Fair Access Day",
            dateTime = "June 4, 2026, 8:30 AM - 4:00 PM",
            venue = "Convention Hall B",
            status = "Approved",
            registeredCount = 210,
            enteredCount = 0,
            attendedCount = 0,
            exitedCount = 0,
            noShowCount = 210,
            totalTransactions = 0,
            rejectedScans = 0,
            benefitClaims = 0,
            boothSessionVisits = 0,
            rewardRedemptions = 0,
            totalPointsAwarded = 0,
            idTemplateStatus = "Needs review",
            rewardsStatus = "Draft rules",
            staffCount = 3,
            scanPurposesCount = 4,
        ),
    )

    val attendees = listOf(
        OrganizerMvpAttendee(
            id = "att-001",
            eventId = "evt-tech-2026",
            name = "Alyssa Reyes",
            email = "alyssa.reyes@example.com",
            phone = "+63 917 555 0101",
            registrationStatus = "Registered",
            currentEventStatus = "Entered / Checked-in",
            points = 35,
            lastTransactionTime = "May 26, 2026 9:42 AM",
            qrCredentialStatus = "Active",
            recentTransactions = listOf("Entry scan approved", "Attendance scan approved", "Booth Visit: Cloud Lab"),
        ),
        OrganizerMvpAttendee(
            id = "att-002",
            eventId = "evt-tech-2026",
            name = "Marco Santos",
            email = "marco.santos@example.com",
            phone = "+63 918 555 0140",
            registrationStatus = "Registered",
            currentEventStatus = "Attended",
            points = 60,
            lastTransactionTime = "May 26, 2026 10:15 AM",
            qrCredentialStatus = "Active",
            recentTransactions = listOf("Entry scan approved", "Benefit Claim: Meal stub", "Reward Redemption: Lanyard"),
        ),
        OrganizerMvpAttendee(
            id = "att-003",
            eventId = "evt-tech-2026",
            name = "Dana Lim",
            email = "dana.lim@example.com",
            phone = "+63 919 555 0188",
            registrationStatus = "Registered",
            currentEventStatus = "No-show",
            points = 0,
            lastTransactionTime = "No transactions yet",
            qrCredentialStatus = "Issued",
            recentTransactions = emptyList(),
        ),
        OrganizerMvpAttendee(
            id = "att-004",
            eventId = "evt-career-2026",
            name = "Jules Mendoza",
            email = "jules.mendoza@example.com",
            phone = "+63 920 555 0133",
            registrationStatus = "Registered",
            currentEventStatus = "Registered",
            points = 0,
            lastTransactionTime = "No transactions yet",
            qrCredentialStatus = "Pending delivery",
            recentTransactions = emptyList(),
        ),
    )

    val transactions = listOf(
        OrganizerMvpTransaction(
            id = "txn-1001",
            eventId = "evt-tech-2026",
            eventTitle = "Tech Summit 2026",
            attendeeId = "att-001",
            attendeeName = "Alyssa Reyes",
            staffId = "staff-001",
            staffName = "Nina Cruz",
            scanPurpose = "Entry",
            type = "Entry",
            timestamp = "May 26, 2026 9:42 AM",
            status = "Success",
            reason = "Entry accepted",
        ),
        OrganizerMvpTransaction(
            id = "txn-1002",
            eventId = "evt-tech-2026",
            eventTitle = "Tech Summit 2026",
            attendeeId = "att-002",
            attendeeName = "Marco Santos",
            staffId = "staff-002",
            staffName = "Leo Tan",
            scanPurpose = "Benefit Claim",
            type = "Benefit Claim",
            timestamp = "May 26, 2026 10:15 AM",
            status = "Success",
            reason = "Meal stub claimed",
        ),
        OrganizerMvpTransaction(
            id = "txn-1003",
            eventId = "evt-tech-2026",
            eventTitle = "Tech Summit 2026",
            attendeeId = "att-999",
            attendeeName = "Unknown attendee",
            staffId = "staff-003",
            staffName = "Rae Gomez",
            scanPurpose = "Entry",
            type = "Rejected/Invalid",
            timestamp = "May 26, 2026 10:21 AM",
            status = "Rejected",
            reason = "Wrong event QR",
        ),
    )

    val staff = listOf(
        OrganizerMvpStaff(
            id = "staff-001",
            name = "Nina Cruz",
            email = "nina.cruz@example.com",
            assignedEventId = "evt-tech-2026",
            assignedEvent = "Tech Summit 2026",
            accessStatus = "Enabled",
            permissions = listOf("Entry scans", "Attendance scans", "Benefit claims"),
        ),
        OrganizerMvpStaff(
            id = "staff-002",
            name = "Leo Tan",
            email = "leo.tan@example.com",
            assignedEventId = "evt-tech-2026",
            assignedEvent = "Tech Summit 2026",
            accessStatus = "Enabled",
            permissions = listOf("Booth/session visits", "Reward redemption"),
        ),
    )

    val availableUsers = listOf(
        OrganizerMvpStaff(
            id = "user-100",
            name = "Mika Dela Cruz",
            email = "mika.dc@example.com",
            assignedEventId = "",
            assignedEvent = "Not assigned",
            accessStatus = "Available",
            permissions = emptyList(),
        ),
        OrganizerMvpStaff(
            id = "user-101",
            name = "Andre Villanueva",
            email = "andre.v@example.com",
            assignedEventId = "",
            assignedEvent = "Not assigned",
            accessStatus = "Available",
            permissions = emptyList(),
        ),
    )

    val scanPurposes = listOf(
        OrganizerMvpScanPurpose("Entry", true, "Prevent duplicate entry", false, false, 0, "Gate"),
        OrganizerMvpScanPurpose("Attendance", true, "Allow once per day", false, true, 20, "Session"),
        OrganizerMvpScanPurpose("Benefit Claim", true, "Prevent duplicate benefit claim", false, false, 0, "Benefit"),
        OrganizerMvpScanPurpose("Booth/Session Visit", true, "Allow one per booth/session", true, true, 10, "Booth or session"),
        OrganizerMvpScanPurpose("Reward Redemption", true, "Prevent duplicate reward claim", false, false, 0, "Reward"),
        OrganizerMvpScanPurpose("Exit", true, "Allow latest exit update", true, false, 0, "Exit gate"),
    )
}

data class OrganizerMvpEvent(
    val id: String,
    val title: String,
    val dateTime: String,
    val venue: String,
    val status: String,
    val registeredCount: Int,
    val enteredCount: Int,
    val attendedCount: Int,
    val exitedCount: Int,
    val noShowCount: Int,
    val totalTransactions: Int,
    val rejectedScans: Int,
    val benefitClaims: Int,
    val boothSessionVisits: Int,
    val rewardRedemptions: Int,
    val totalPointsAwarded: Int,
    val idTemplateStatus: String,
    val rewardsStatus: String,
    val staffCount: Int,
    val scanPurposesCount: Int,
)

data class OrganizerMvpAttendee(
    val id: String,
    val eventId: String,
    val name: String,
    val email: String,
    val phone: String,
    val registrationStatus: String,
    val currentEventStatus: String,
    val points: Int,
    val lastTransactionTime: String,
    val qrCredentialStatus: String,
    val recentTransactions: List<String>,
)

data class OrganizerMvpTransaction(
    val id: String,
    val eventId: String,
    val eventTitle: String,
    val attendeeId: String,
    val attendeeName: String,
    val staffId: String,
    val staffName: String,
    val scanPurpose: String,
    val type: String,
    val timestamp: String,
    val status: String,
    val reason: String,
)

data class OrganizerMvpStaff(
    val id: String,
    val name: String,
    val email: String,
    val assignedEventId: String,
    val assignedEvent: String,
    val accessStatus: String,
    val permissions: List<String>,
)

data class OrganizerMvpScanPurpose(
    val label: String,
    val enabled: Boolean,
    val duplicateRule: String,
    val trackingOnly: Boolean,
    val pointsEnabled: Boolean,
    val pointsValue: Int,
    val requiredSelectionLabel: String,
)
